/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-2",
    "aws_cognito_identity_pool_id": "us-east-2:387008c2-55bc-409f-9f51-a07d9fb59b1e",
    "aws_cognito_region": "us-east-2",
    "aws_user_pools_id": "us-east-2_wYCPGY0q0",
    "aws_user_pools_web_client_id": "2pkhklbau4ocqh0lvoa69m7453",
    "oauth": {}
};


export default awsmobile;
